/*
 * Author: Pixelated_Grunt
 * Description: Include file contains all arsenal whitelisted items
 *
 */


if !(isServer) exitWith {};

//ACE3 items
private _ace3Items = ["milgp_f_face_shield_shades_khk", "ACE_UAVBattery", "ACE_Altimeter", "ACE_quikclot", "ACE_Kestrel4500", "ACE_MRE_LambCurry", "milgp_f_face_shield_MC", "milgp_f_face_shield_shades_shemagh_MC", "ACE_Cellphone", "ACE_epinephrine", "ACE_Clacker", "milgp_f_face_shield_shades_CB", "milgp_f_face_shield_shades_BLK", "milgp_f_face_shield_RGR", "milgp_f_face_shield_khk", "ACE_bloodIV_250", "ACE_salineIV_250", "ACE_packingBandage", "ACE_plasmaIV_250", "milgp_f_face_shield_shades_shemagh_BLK", "ACE_ATragMX", "ACE_personalAidKit", "ACE_CableTie", "milgp_f_face_shield_shades_shemagh_khk", "milgp_f_face_shield_shades_MC", "ACE_suture", "ACE_MRE_BeefStew", "ACE_DefusalKit", "milgp_f_face_shield_CB", "ACE_wirecutter", "ACE_WaterBottle", "ACE_M26_Clacker", "ACE_EarPlugs", "ACE_IR_Strobe_Item", "ACE_tourniquet", "ACE_morphine", "ACE_RangeCard", "ACE_surgicalKit", "milgp_f_face_shield_BLK", "ACE_Canteen", "ACE_bloodIV", "ACE_plasmaIV_500", "ACE_salineIV", "ACE_fieldDressing", "milgp_f_face_shield_shades_shemagh_RGR", "ACE_plasmaIV", "ACE_salineIV_500", "milgp_f_face_shield_shades_RGR", "ACE_DAGR", "ACE_NVG_Wide_Black", "milgp_f_face_shield_shades_shemagh_CB", "ACE_bloodIV_500", "ACE_Flashlight_XL50", "ACE_MRE_ChickenTikkaMasala", "ACE_bodyBag", "ACE_elasticBandage", "ACE_Flashlight_MX991", "ACE_splint", "ACE_SpraypaintRed", "ACE_MapTools", "ACE_adenosine", "ACE_EntrenchingTool", "ACE_M84", "ACE_Chemlight_HiGreen", "ACE_Chemlight_HiRed", "ACE_Chemlight_HiYellow", "ACE_M14", "ACE_FlareTripMine_Mag", "ACE_40mm_Flare_white", "ACE_SpareBarrel", "ACE_painkillers", "ace_30rnd_556x45_stanag_m995_ap_mag", "ACE_Chemlight_IR", "ACE_CTS9", "ACE_VMH3", "ACE_Flashlight_Maglite_ML300L"];

//ACRE2 items
private _acre2Items = ["ACRE_PRC343", "ACRE_PRC152", "ACRE_PRC117F"];

//CUP items
private _cupItems = ["CUP_B_AFU_IIID_MM14", "CUP_B_Raid_bag_SSO_Ataka_2_Green", "CUP_muzzle_mfsup_SCAR_L", "CUP_muzzle_mfsup_Flashhider_556x45_Tan", "CUP_muzzle_mfsup_Flashhider_556x45_Black", "CUP_optic_AIMM_MARS_TAN", "CUP_optic_AIMM_MARS_BLK", "CUP_optic_AIMM_MICROT1_TAN", "CUP_optic_AIMM_MICROT1_BLK", "CUP_G_ESS_BLK_Facewrap_Black", "CUP_U_C_Tracksuit_02", "CUP_optic_AN_PVS_4", "CUP_acc_LLM_black", "CUP_H_PMC_Beanie_Winter", "CUP_acc_LLM01_L", "CUP_I_B_PMC_Unit_34", "CUP_G_Oakleys_Drk", "CUP_SOFLAM", "CUP_U_C_Suit_01", "CUP_optic_LeupoldMk4_25x50_LRT", "CUP_acc_ANPEQ_15_Black", "CUP_optic_AN_PVS_10_black", "CUP_H_PMC_Beanie_Khaki", "CUP_U_B_BAF_DPM_GHILLIE", "CUP_acc_Glock17_Flashlight", "CUP_acc_ANPEQ_15_Top_Flashlight_Black_L", "CUP_optic_TrijiconRx01_black", "CUP_bipod_Harris_1A2_L_BLK", "CUP_H_Ger_Beret_ARM_Grn", "CUP_optic_ACOG_TA01NSN_RMR_Black", "CUP_optic_PGO7V", "CUP_H_RUS_Cap_ATACSAU", "CUP_optic_PGO7V3", "CUP_optic_MAAWS_Scope", "CUP_muzzle_snds_AWM", "CUP_H_PMC_Beanie_Black", "CUP_optic_Elcan_SpecterDR_RMR_black", "CUP_muzzle_snds_M9", "CUP_optic_PGO7V2", "CUP_G_PMC_RadioHeadset", "CUP_NVG_PVS15_black", "CUP_1Rnd_StarCluster_Green_M203", "CUP_FlareWhite_M203", "CUP_OG7_M", "CUP_PG7V_M", "CUP_50Rnd_570x28_Red_Tracer_P90_M", "CUP_8Rnd_12Gauge_Pellets_No0_Buck", "CUP_PipeBomb_M", "CUP_1Rnd_StarFlare_Green_M203", "CUP_PG7VL_M", "CUP_1Rnd_SmokeGreen_M203", "CUP_1Rnd_StarFlare_Red_M203", "CUP_PG7VM_M", "CUP_17Rnd_9x19_glock17", "CUP_30Rnd_556x45_PMAG_BLACK", "CUP_1Rnd_Smoke_M203", "CUP_30Rnd_9x19_MP5", "CUP_PG7VR_M", "CUP_1Rnd_HE_M203", "CUP_1Rnd_SmokeRed_M203", "CUP_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M", "CUP_20Rnd_TE1_Red_Tracer_762x51_M110", "CUP_1Rnd_StarCluster_Red_M203", "CUP_5Rnd_86x70_L115A1", "CUP_30Rnd_556x45_Stanag_Tracer_Red", "CUP_8Rnd_12Gauge_Slug", "CUP_TBG7V_M", "CUP_200Rnd_TE4_Red_Tracer_556x45_M249", "CUP_30Rnd_Red_Tracer_9x19_MP5", "CUP_20Rnd_762x51_L129_M", "CUP_HandGrenade_M67", "CUP_MAAWS_HEDP_M", "CUP_MAAWS_HEAT_M", "CUP_8Rnd_12Gauge_HE", "CUP_1Rnd_StarFlare_White_M203", "CUP_30Rnd_556x45_Stanag_Mk16_black", "CUP_lmg_L110A1", "CUP_arifle_M4A1_MOE_short_black", "CUP_arifle_HK416_CQB_M203_Black", "CUP_sgun_M1014", "CUP_launch_FIM92Stinger", "CUP_lmg_L7A2_Flat", "CUP_launch_MAAWS", "CUP_launch_M72A6", "CUP_launch_RPG7V", "CUP_lmg_minimi_railed", "CUP_hgun_Glock17_blk", "CUP_srifle_L129A1", "CUP_arifle_M4A1_SOMMOD_black", "CUP_srifle_AWM_blk", "CUP_arifle_M4A1_BUIS_GL", "CUP_arifle_HK416_Black"];

//Community Factions Project items
private _cfpItems = ["CFP_AssaultPack_White", "SP_Carryall_White", "CFP_Shemagh_Full_Black", "CFP_Polo_Liverpool", "SP_BaseballCap_Black", "SP_Modular2_White", "SP_Balaclava_Skull2", "CFP_Lungee_BlueGrey"];

//GreenMag items
private _greenmagItems = ["greenmag_ammo_762x51_basic_30Rnd", "greenmag_ammo_762x51_basic_60Rnd", "greenmag_ammo_570x28_basic_60Rnd", "greenmag_ammo_556x45_tracer_60Rnd", "greenmag_beltlinked_762x51_basic_100", "greenmag_ammo_556x45_m995ap_60Rnd", "greenmag_ammo_556x45_m995ap_30Rnd", "greenmag_ammo_556x45_basic_30Rnd", "greenmag_beltlinked_556x45_basic_200", "greenmag_ammo_556x45_basic_60Rnd", "greenmag_ammo_570x28_basic_30Rnd", "greenmag_ammo_556x45_tracer_30Rnd", "greenmag_item_speedloader"];

//Hates camera items
private _hatesItems = ["Old_Camera_HUD", "Old_Camera_Color_HUD", "Hate_Smartphone_HUD", "Old_Camera_Color", "Hate_Smartphone", "Old_Camera", "Nikon_DSLR", "Nikon_DSLR_HUD"];

//KAT Advanced Medical items
private _katItems = ["kat_phenylephrineAuto", "kat_suction", "kat_aatKit", "kat_amiodarone", "kat_phenylephrine", "kat_naloxone", "kat_mask_M50", "kat_chestSeal", "kat_atropine", "kat_pocketBVM", "kat_MFAK", "kat_ncdKit", "kat_IV_16", "kat_AED", "kat_AFAK", "kat_epinephrineIV", "kat_Pulseoximeter", "kat_IO_FAST", "kat_accuvac", "kat_TXA", "kat_larynx", "KAT_Empty_bloodIV_250", "kat_ultrasound", "kat_lidocaine", "kat_sealant", "kat_guedel", "kat_EACA", "kat_BVM", "kat_norepinephrine", "kat_vacuum", "kat_gasmaskFilter", "kat_reboa", "kat_ketamine", "KAT_Empty_bloodIV_500", "kat_X_AED", "kat_oxygenTank_300", "kat_Penthrox", "kat_Carbonate", "kat_oxygenTank_150", "kat_Painkiller", "kat_Pervitin", "kat_Caffeine"];

//Military Gear Pack items
private _mgpItems = ["milgp_b_patrol_01_rgr", "milgp_u_tshirt_g3_field_pants_mc", "tacs_milgp_mmac_grenadier_belt_blk", "milgp_v_mmac_assaulter_belt_rgr", "milgp_v_mmac_teamleader_belt_rgr", "milgp_u_pcu_g3_field_pants_mcarid", "milgp_u_tshirt_g3_field_pants_atacsau", "milgp_v_mmac_marksman_belt_rgr", "milgp_u_g3_field_set_mcarid", "tacs_milgp_mmac_marksman_belt_blk", "milgp_u_g3_field_set_mc", "milgp_v_mmac_hgunner_belt_rgr", "tacs_milgp_mmac_assaulter_belt_blk", "tacs_milgp_mmac_hgunner_belt_blk", "milgp_u_g3_field_set_mcalpine", "milgp_u_pcu_g3_field_pants_mc", "milgp_v_mmac_medic_belt_rgr", "tacs_milgp_mmac_medic_belt_blk", "milgp_u_tshirt_g3_field_pants_3CD", "milgp_v_mmac_grenadier_belt_rgr", "milgp_u_tshirt_g3_field_pants_mcarid", "milgp_u_g3_field_set_rolled_mcarid", "tacs_milgp_mmac_teamleader_belt_blk", "milgp_u_tshirt_g3_field_pants_khk", "milgp_u_g3_field_set_rolled_mc"];

//Theseus Services items
private _tacsItems = ["tacs_Backpack_Carryall_White", "tacs_Backpack_Kitbag_Medic_White", "tacs_Uniform_Combat_RS_CDFS_GP_TB", "tacs_Helmet_Enc_Ballistic_DarkBlack", "tacs_Uniform_Combat_LS_GS_GP_BB", "tacs_Uniform_Combat_RS_CBPS_BP_BB", "tacs_Uniform_Combat_RS_GS_GP_BB", "tacs_Uniform_Combat_LS_WS_WP_WB", "tacs_Uniform_Combat_LS_TS_TP_TB", "tacs_Helmet_Enc_Ballistic_White", "tacs_Uniform_Combat_RS_BS_BP_BB", "tacs_Uniform_Combat_LS_CDFS_GP_TB", "tacs_Uniform_Combat_RS_CLRS_TP_BB", "tacs_Uniform_Combat_LS_BS_BP_BB", "tacs_Uniform_Combat_LS_CBPS_BP_BB", "tacs_Uniform_Combat_LS_CLES_TP_BB", "tacs_Uniform_Combat_RS_CLES_TP_BB", "tacs_Uniform_Combat_RS_TS_TP_TB", "tacs_Uniform_Combat_LS_CLRS_TP_BB"];

//Generic items
private _genericItems = ["SMG_03C_TR_black", "SmokeShell", "Laserbatteries", "APERSMine_Range_Mag", "50Rnd_570x28_SMG_03", "ClaymoreDirectionalMine_Remote_Mag", "SmokeShellYellow", "SmokeShellRed", "DemoCharge_Remote_Mag", "ItemMicroDAGR", "ItemCompass", "muzzle_snds_570", "H_HelmetSpecB_sand", "ItemGPS", "G_B_Diving", "ItemcTabHCam", "G_Aviator", "Laserdesignator", "ItemcTab", "G_Bandanna_RedFlame1", "Attachable_Helistretcher", "Binocular", "H_HelmetSpecB_paint1", "optic_Hamr", "muzzle_snds_B", "grad_paceCountBeads_functions_paceCountBeads", "ToolKit", "H_HelmetB_black", "G_Balaclava_blk", "ItemAndroid", "muzzle_snds_M", "U_B_Wetsuit", "muzzle_snds_L", "H_HelmetSpecB", "ItemMap", "ItemWatch", "B_UavTerminal", "V_RebreatherB", "B_Parachute", "B_Carryall_blk"];

//Complete list
private _fullList = _ace3Items + _acre2Items + _cupItems + _cfpItems + _greenmagItems + _hatesItems + _katItems + _mgpItems + _tacsItems + _genericItems;

//diag_log("XDF [MF] INFO: Setting up XDF_virtualItems variable.");
missionNamespace setVariable ["XDF_virtualItems", _fullList]
